### ISSUE TITLE
Feature request : Neo Geo Core

### ISSUE THREAD

**Issue by cticitai** [MiSTer-DE1-SoC/Main_MiSTer#1]

**Comment by mazsola2k** [comment]
Ported just today morning Neo Geo Core for DE1-SoC FPGA, publishing Today on github and modernhackers.com.
Thanks for the ask!

**Comment by mazsola2k** [comment]
**Here you go, NeoGeo ported to DE1-Soc:**
https://github.com/MiSTer-DE1-SoC/NeoGeo_MiSTer
Do not forget to update the Menu Mister and Main and System Software:
https://github.com/MiSTer-DE1-SoC/Menu_MiSTer
https://github.com/MiSTer-DE1-SoC/Main_MiSTer

I would recommend to go with the latest SD Installer for DE1-SoC, easier, this contains the latest Menu and Main files that compatible with NeoGeo:
https://github.com/MiSTer-DE1-SoC/SD-Installer-Win64_MiSTer

**Comment by manast** [comment]
@mazsola2k I installed the latest files but the only thing I could make work is the OSD itself, no games would boot after loading them, I filled a separate issue for this #5
