### ISSUE TITLE
Porting of MiSTer to a MAX10 board like DE10-lite

### ISSUE THREAD

**Issue by bjoelkrug78** [MiSTer-DE1-SoC/Main_MiSTer#2]
Hi there!

I am following the development of the MiSTer ports to DE10-Standard and DE1-SoC very closely. I am a FPGA developer myself and just got hold of a DE10-lite board with the MAX10 on it.
I know it doesn't have any HPS, but has SDRAM on board connecting to the FPGA.
Would it be possible to port over MiSTer in easier form to this board? I would really start getting to this but probably need some initial feedback.
I am thinking of not using any HPS for loading programs etc, so everything at the beginning would have to be hardcoded.

Cheers,
Berni

**Comment by mazsola2k** [comment]
> Hi there!
> 
> I am following the development of the MiSTer ports to DE10-Standard and DE1-SoC very closely. I am a FPGA developer myself and just got hold of a DE10-lite board with the MAX10 on it.
> I know it doesn't have any HPS, but has SDRAM on board connecting to the FPGA.
> Would it be possible to port over MiSTer in easier form to this board? I would really start getting to this but probably need some initial feedback.
> I am thinking of not using any HPS for loading programs etc, so everything at the beginning would have to be hardcoded.
> 
> Cheers,
> Berni

Hi Berni,

The most important features of MiSTer Platform are the SDCard+USB devices handling through HPS. If you are not using HPS you have-to implement natively, and SDCard is more difficult, you have to implement a native FPGA SDCARD controller.
So if you do not have a HPS compatible board, maybe better to run the earlir generation FPGA builds, earlier than MiSTer, for example MiST (https://github.com/mist-devel), 
or go to the original source where all FPGA games cames from and you can port directly to your non HPS compatible board (for example Minimig on DE1 https://github.com/rkrajnc/minimig-de1)

Best regards,

Mazsola2k
