### ISSUE TITLE
Upgrade SNES Core

### ISSUE THREAD

**Issue by manast** [MiSTer-DE1-SoC/Main_MiSTer#4]
After resolving issue #3 I am now testing with the SNES core, and it almost looks correct but every second or so there is some screen "glitch" that seems to come from some kind of out-of-sync thing. The Neogeo core does not exhibit this effect, but since there is a new SNES core from November, it would be great if you could upgrade the DE1-SOC version of it to the latest. I also noticed that Yoshi's Island is not working in the current version, not sure why, maybe it is also due to a too old version.

**Comment by mazsola2k** [comment]
https://github.com/MiSTer-DE1-SoC/SNES_MiSTer

> This SNES Core is an experimental SNES release, because in the original MiSTer Core SNES project the FPGA memory management moved from WRAM to BRAM version. The original srg320 snes fpga project used Cyclone III which used m9k as block type with less FPGA memory usage, while DE10-Nano and DE10-Standard builds are utilizing now 98% of FPGA memory blocks with using m10k block type for all dpram blocks defined in the latest builds. Due to the fact that DE1-Soc has a bit less FPGA memory cells till m10k block type is the only way to implement bi directional ram type in the main builds, so went back to 162718dc1af2180cae0432b775d2b103f497a0f8 commit that used less FPGA memory, until DPRAM is the only supported RAM type in SNES Core.

Until SNES core is not targeting real SDRAM instead of FPGA Blockram (BRAM), the SNES is not fitting to DE1-SoC, only to DE10-Standard DE10-Nano and Arrow SoCKit FPGA-s.

**Comment by manast** [comment]
but it is working perfectly using standard VGA with scandoubler... it is only the 15Khz output that is not working.

**Comment by mazsola2k** [comment]
> but it is working perfectly using standard VGA with scandoubler... it is only the 15Khz output that is not working.

Hoping that in the near future most of the MiSTer cores are utilizing the SDRAM instead of Bram then DE1-SoC can run the recent SNES core.
The DE1-SoC builds targeted with scandoubler on and vga scaler on, not tested without them. You can try to turn off in the MiSTer.ini but not aimed to get working without them.

**Comment by manast** [comment]
It is tested as I mentioned already in issue #3. And it almost works. Check this animated gif:

![ezgif com-optimize](https://user-images.githubusercontent.com/95200/71673682-b5a4f180-2d79-11ea-9a3b-8979785c7822.gif)

**Comment by manast** [comment]
Seems like snes core is using sdram now, or I am mistaken? https://github.com/MiSTer-devel/SNES_MiSTer/commit/22cad702f04312bd94d41ae4ef70c1561ef5dcd4
