### ISSUE TITLE
NEOGEO Core not working? (or improper rom files...)

### ISSUE THREAD

**Issue by manast** [MiSTer-DE1-SoC/Main_MiSTer#5]
Hello,

I tried the core and sadly does not seem to work properly. The OSD menu appears, however there is no ROM that works, the screen just is kept black. I tried several roms from the Darksoft rom pack, they seem to load according to the indicators in the top left of the screen, however the game does not boot. I tried both with the unibios as well as stock neogeo roms with no difference either.
I tried both in CRT screen and LCD, same thing on both.

Did you manage to make it work?

**Comment by MiSTer-Arrow-SoCKit** [comment]
Regarding roms the best you can find is Everdrive/Darksoft NeoGeo

Regarding BIOS settings:
Console (AES)
BIOS: Unibios

Regarding BIOS files:
000-lo.lo (128kb)
neo-epo.sp1 (128kb)
sfix.sfix (128kb)
sp-s2.sp1 (128kb)
uni-bios.rom (128kb)

Romset xml for Metal Slug:
<romsets>
	<romset name="mslug" pcm="1" altname="Metal Slug - Super Vehicle-001" publisher="Nazca" year="1996"/>
	<romset name="mslug2" pcm="1" altname="Metal Slug 2 - Super Vehicle-001-II" publisher="SNK" year="1998"/>
	<romset name="mslug3" cmc="1" sma="4" pcm="1" altname="Metal Slug 3" publisher="Nazca" year="2000" ram="2"/>
        <romset name="mslug4,mslug4h" cmc="1" pcm="1" altname="Metal Slug 4" publisher="SNK" year="1991" ram="1"/>
	<romset name="mslug5,mslug5h" pvc="1" pcm="1" altname="Metal Slug 5" publisher="?" year="2003" ram="2"/>
	<romset name="mslugx" pcm="1" altname="Metal Slug X - Super Vehicle-001" publisher="SNK" year="1999" ram="1"/>
</romsets>

You can check on youtube as a result:
DE1-SOC: https://www.youtube.com/watch?v=umQQ8exeL2s
DE10-Standard: https://www.youtube.com/watch?v=7FWoLRz-tR4

**Comment by mazsola2k** [comment]
> owever the game does not boot. I tried both with the unibios as well as stock neogeo roms with no difference either.

Regarding roms the best you can find is Everdrive/Darksoft NeoGeo

Regarding BIOS settings:
Console (AES)
BIOS: Unibios

Regarding BIOS files:
000-lo.lo (128kb)
neo-epo.sp1 (128kb)
sfix.sfix (128kb)
sp-s2.sp1 (128kb)
uni-bios.rom (128kb)

Romset xml for Metal Slug:
```
<romsets>
	<romset name="mslug" pcm="1" altname="Metal Slug - Super Vehicle-001" publisher="Nazca" year="1996"/>
	<romset name="mslug2" pcm="1" altname="Metal Slug 2 - Super Vehicle-001-II" publisher="SNK" year="1998"/>
	<romset name="mslug3" cmc="1" sma="4" pcm="1" altname="Metal Slug 3" publisher="Nazca" year="2000" ram="2"/>
        <romset name="mslug4,mslug4h" cmc="1" pcm="1" altname="Metal Slug 4" publisher="SNK" year="1991" ram="1"/>
	<romset name="mslug5,mslug5h" pvc="1" pcm="1" altname="Metal Slug 5" publisher="?" year="2003" ram="2"/>
	<romset name="mslugx" pcm="1" altname="Metal Slug X - Super Vehicle-001" publisher="SNK" year="1999" ram="1"/>
</romsets>
```

You can check on youtube as a result:
DE1-SOC: https://www.youtube.com/watch?v=umQQ8exeL2s
DE10-Standard: https://www.youtube.com/watch?v=7FWoLRz-tR4

**Comment by manast** [comment]
thanks for the answer. I think I have the bios and roms in the proper format, does this look correct for example:
![image](https://user-images.githubusercontent.com/95200/71601014-ec98be80-2b51-11ea-94b2-906d1f1425f0.png)

**Comment by manast** [comment]
And the BIOS files looks like these:
![image](https://user-images.githubusercontent.com/95200/71601100-45685700-2b52-11ea-894e-cb5ddad766c3.png)

**Comment by mazsola2k** [comment]
**on linux side, please validate with md5sum command:**

`fc7599f3f871578fe9a0453662d1c966  000-lo.lo
a7b798c9cafb1aba49090bca34e1d4ec  neo-epo.sp1
aa2b5d0eae4158ffc0d7d63481c7830b  sfix.sfix
2968f59f44bf328639aa79391aeeeab4  sp-s2.sp1
bfc6563dde345d68da2623dc7f0f12d3  uni-bios.rom

4ab6f4c96b159aa57b6737cc17cace70  mslug/crom0
6512bd43d9caa6e02c990b0a82652dca  mslug/fpga
6449db0459bcf7584348792009e8f12c  mslug/m1rom
b376f699c2b3e32cc78d967afd41251f  mslug/prom
59b0200b7ed4f9704e6f34fa6d05796e  mslug/srom
e2915bdd16e3bd1007fd949a4f594df  mslug/vroma0`
